menu:
  主页: 
  文档: categories/文档
  随写: categories/随写
  标签: tags
  归档: archives

weibo: http://weibo.com/bpskong

github: https://github.com/bpskong

duoshuo: bpskong

jiathis:
  uid: 1796651
  tsina: 2036985411
